-- Version: 1 Loans base tables
-- CUSTOMER table
CREATE TABLE CUSTOMER (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    SURNAME VARCHAR(100) NOT NULL,
    CREDIT_LIMIT DECIMAL(12, 2) NOT NULL,
    USED_CREDIT_LIMIT DECIMAL(12, 2) NOT NULL DEFAULT 0
);

-- LOAN table
CREATE TABLE LOAN (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CUSTOMER_ID INT NOT NULL REFERENCES CUSTOMER(ID),
    LOAN_AMOUNT DECIMAL(12, 2) NOT NULL,
    NUMBER_OF_INSTALLMENTS SMALLINT NOT NULL,
    PAID BOOLEAN NOT NULL DEFAULT FALSE,
    CREATE_DATE TIMESTAMP NOT NULL
);

-- LOAN_INSTALLMENT table
CREATE TABLE LOAN_INSTALLMENT (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    LOAN_ID BIGINT NOT NULL REFERENCES LOAN(ID),
    AMOUNT DECIMAL(12, 2) NOT NULL,
    PAID_AMOUNT DECIMAL(12, 2) NOT NULL DEFAULT 0,
    DUE_DATE DATE NOT NULL,
    PAYMENT_DATE DATE,
    PAID BOOLEAN NOT NULL DEFAULT FALSE

    CHECK (PAID = FALSE OR (PAID_AMOUNT > 0 AND PAYMENT_DATE IS NOT NULL)),
    CHECK (AMOUNT > 0),
    CHECK (PAID_AMOUNT >= 0)
);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, CREDIT_LIMIT)
VALUES (100001, 'Isik', 'Erhan', 10000000.00);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, CREDIT_LIMIT)
VALUES (100002, 'John', 'Doe', 500000.00);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, CREDIT_LIMIT)
VALUES (100003, 'Jane', 'Doe', 7500000.00);